var menu = [
    {
        id: 1,
        name: 'Giày Boot Nữ  1',
        image: 'NU-BOOT-01.jpg',
        price: 120000,
        best:true,
        boot : true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 2,
        name: 'Giày Boot Nữ  2',
        image: 'NU-BOOT-02.jpg',
        price: 140000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 3,
        name: 'Giày Boot Nữ  3',
        image: 'NU-BOOT-03.jpg',
        price: 220000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 4,
        name: 'Giày Boot Nữ  4',
        image: 'NU-BOOT-04.jpg',
        price: 123000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 5,
        name: 'Giày Boot Nữ  5',
        image: 'NU-BOOT-03.jpg',
        price: 320000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 6,
        name: 'Giày Boot Nữ  6',
        image: 'NU-BOOT-03.jpg',
        price: 170000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 7,
        name: 'Giày Boot Nữ  7',
        image: 'NU-BOOT-03.jpg',
        price: 110000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 8,
        name: 'Giày Boot Nữ  8',
        image: 'NU-BOOT-03.jpg',
        price: 150000,
        best:true,
        boot :true,
        sneakerN : false,
        nu : true,
    },
    {
        id: 9,
        name: 'Giày Thể Thao Nam 1 ',
        image: 'N-TT-01.jpg',
        price: 155000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 10,
        name: 'Giày Thể Thao Nam 2 ',
        image: 'N-TT-03.jpg',
        price: 133000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 11,
        name: 'Giày Thể Thao Nam 3 ',
        image: 'N-TT-01.jpg',
        price: 175000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 12,
        name: 'Giày Thể Thao Nam 4 ',
        image: 'N-TT-03.jpg',
        price: 190000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 13,
        name: 'Giày Thể Thao Nam 5 ',
        image: 'N-TT-01.jpg',
        price: 199000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 14,
        name: 'Giày Thể Thao Nam 6 ',
        image: 'N-TT-03.jpg',
        price: 188000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 15,
        name: 'Giày Thể Thao Nam 7 ',
        image: 'N-TT-01.jpg',
        price: 179000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 16,
        name: 'Giày Thể Thao Nam 8 ',
        image: 'N-TT-02.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : true,
        nu : false,
    },
    {
        id: 17,
        name: 'Giày Cao Gót 1 ',
        image: 'CG-1.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 18,
        name: 'Giày Cao Gót 2 ',
        image: 'CG-2.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 19,
        name: 'Giày Cao Gót 3 ',
        image: 'CG-3.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 20,
        name: 'Giày Cao Gót 4 ',
        image: 'CG-4.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 21,
        name: 'Giày Cao Gót 5 ',
        image: 'CG-5.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 22,
        name: 'Giày Cao Gót 6 ',
        image: 'CG-6.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 23,
        name: 'Giày Cao Gót 7 ',
        image: 'CG-7.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    {
        id: 24,
        name: 'Giày Cao Gót 8 ',
        image: 'CG-8.jpg',
        price: 100000,
        best:true,
        boot :false,
        sneakerN : false,
        cg : true,
        nu : true,
    },
    

]
